name: Flask Application CI

on:
  push:
    branches:
      - main  # Main branch'a yapılan her push için çalıştır
  pull_request:
    branches:
      - main  # PR açıldığında çalıştır

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Kodunuzu çekin
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Docker Buildx kurulumu için
      
    - name: Build and run Flask application
      run: |
        docker build -t flask-app:latest .
        docker run -d -p 5000:5000 flask-app
        
    - name: Verify application is running
      run: curl http://localhost:5000
